//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKAProject.Styles {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class StatusBadgeStyle : global::System.Configuration.ApplicationSettingsBase {
        
        private static StatusBadgeStyle defaultInstance = ((StatusBadgeStyle)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new StatusBadgeStyle())));
        
        public static StatusBadgeStyle Default {
            get {
                return defaultInstance;
            }
        }
    }
}
